name: Coverage
on: push

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-mpl
          pip install poetry==1.*
          poetry install
      - name: Test with pytest
        run: |
          poetry run coverage run -m pytest --mpl
          poetry run coverage report -i
          poetry run coverage xml -i
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@main
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
